[package]
name = "day05a"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-crate = { version = "0.1.0", path = "../aoc-crate" }
regex = "1.10.2"
